# This is the main workflow that creates a new image and push to Openshift image stream which in turn triggers the deployment

name: Main - Build Image and Push to Openshift Registry for Dev Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      app1:
        description: 'App Name (jag-ccd-1-1)'    
        required: true
        default: 'jag-ccd-1-1'
      app2:
        description: 'App Name (jag-ccd-1-2)'    
        required: true
        default: 'jag-ccd-1-2'
      env:
        type: choice
        description: Image Target environment
        options: 
        - dev    
        required: true
        default: 'dev'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-push-image:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    environment: ${{ github.event.inputs.env }}
    env:
      BASIC_AUTH_USER: ${{ secrets.BASIC_AUTH_USER }}
      BASIC_AUTH_PASS: ${{ secrets.BASIC_AUTH_PASS }}
      GENERIC_AGENCY_ID: ${{secrets.GENERIC_AGENCY_ID}}
      GENERIC_PART_ID: ${{secrets.GENERIC_PART_ID}}
      FORM_PARAM_IDX: ${{secrets.FORM_PARAM_IDX}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git Checkout
        uses: actions/checkout@v3
      
      # Get the version number which is prefixed with the Github release branches in format release/{version}
      - name: Get Release Version
        run: |
          branch=${GITHUB_REF##*/}
          version=$(echo $branch | cut -d "/" -f2-)
          echo "releaseVersion=$version" >> $GITHUB_ENV
      
      # Get Git latest short Sha# from the release branch used. This Sha# will be used in image tagging as well as DC Pod labelling.
      - name: Get git commit short sha
        id: sha
        run: |
          shortSha=$(echo $(git rev-parse --short HEAD) | cut -c1-7)
          echo "gitsha=$shortSha" >> $GITHUB_ENV
      
      # Prints vital release paramters used
      - name: Print Release Variables
        run: |
          echo "Release Application 1: ${{ github.event.inputs.app1 }}"
          echo "Release Application 2: ${{ github.event.inputs.app2 }}"
          echo "Release Environment: ${{ github.event.inputs.env }}"
          echo "Release Version: ${{ env.releaseVersion }}"
          echo "Release Git Sha: ${{env.gitsha}}"

      # Set up JDK build environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
        
      # Runs build steps
      - name: Maven Package
        run: mvn -ntp clean package
        
      - name: Maven Verify
        run: mvn -ntp clean verify
      
      - name: Maven Spotless Check
        run: mvn -ntp spotless:check

      #Build image jag-ccd-1-1
      - name: Build image jag-ccd-1-1
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./jag-ccd-application-1.1
        run: |
          docker build -t ${{github.event.inputs.app1}}:${{env.gitsha}} ${CONTEXT}
      
      #Build image jag-ccd-1-2
      - name: Build image jag-ccd-1-2
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: ./jag-ccd-application-1.2
        run: |
          docker build -t ${{github.event.inputs.app2}}:${{env.gitsha}} ${CONTEXT}
      
       #Login to OpenShift Container Repository - Silver
      - name: Login to OpenShift Container Repository - Silver
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD_SILVER}}
  
      #Push image jag-ccd-1-1 to OpenShift Image stream - Silver
      - name: Push Image jag-ccd-1-1 to Openshift Image Stream - Silver
        env:
          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE_SILVER}}/${{github.event.inputs.app1}}:${{secrets.OPENSHIFT_ENV_TAG}}
        run: |
          docker tag ${{github.event.inputs.app1}}:${{env.gitsha}} ${IMAGE}
          docker push ${IMAGE}
      
      #Push image jag-ccd-1-2 to OpenShift Image stream - Silver
      - name: Push Image jag-ccd-1-2 to Openshift Image Stream - Silver
        env:
          IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_SILVER}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE_SILVER}}/${{github.event.inputs.app2}}:${{secrets.OPENSHIFT_ENV_TAG}}
        run: |
          docker tag ${{github.event.inputs.app2}}:${{env.gitsha}} ${IMAGE}
          docker push ${IMAGE}

      # #Login to OpenShift Container Repository - Kamloops (OC PROD)
      # - name: Login to OpenShift Container Repository - Kamloops (OC PROD)
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
      #     username: ${{secrets.OPENSHIFT_SA_USERNAME}}
      #     password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      # #Push image jag-ccd-1-1 to OpenShift Image stream - Kamloops (OC Prod)
      # - name: Push Image jag-ccd-1-1 to Openshift Image Stream - Kamloops (OC Prod)
      #   env:
      #     IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/${{github.event.inputs.app1}}:${{secrets.OPENSHIFT_ENV_TAG}}
      #   run: |
      #     docker tag ${{github.event.inputs.app1}}:${{env.gitsha}} ${IMAGE}
      #     docker push ${IMAGE}
      
      # #Push image jag-ccd-1-2 to OpenShift Image stream - Kamloops (OC Prod)
      # - name: Push Image jag-ccd-1-2 to Openshift Image Stream - Kamloops (OC Prod)
      #   env:
      #     IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/${{github.event.inputs.app2}}:${{secrets.OPENSHIFT_ENV_TAG}}
      #   run: |
      #     docker tag ${{github.event.inputs.app2}}:${{env.gitsha}} ${IMAGE}
      #     docker push ${IMAGE}
      
      # #Login to OpenShift Container Repository - Calgary (OC DR)
      # - name: Login to OpenShift Container Repository - Calgary (OC DR)
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_DR}}
      #     username: ${{secrets.OPENSHIFT_SA_USERNAME}}
      #     password: ${{secrets.OPENSHIFT_SA_PASSWORD_DR}}

      # #Push image jag-ccd-1-1 to OpenShift Image stream - Calgary (OC DR)
      # - name: Push Image jag-ccd-1-1 to Openshift Image Stream - Calgary (OC DR)
      #   env:
      #     IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_DR}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/${{github.event.inputs.app1}}:${{secrets.OPENSHIFT_ENV_TAG}}
      #   run: |
      #     docker tag ${{github.event.inputs.app1}}:${{env.gitsha}} ${IMAGE}
      #     docker push ${IMAGE}
      
      # #Push image jag-ccd-1-2 to OpenShift Image stream - Calgary (OC DR)
      # - name: Push Image jag-ccd-1-2 to Openshift Image Stream - Calgary (OC DR)
      #   env:
      #     IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY_DR}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/${{github.event.inputs.app2}}:${{secrets.OPENSHIFT_ENV_TAG}}
      #   run: |
      #     docker tag ${{github.event.inputs.app2}}:${{env.gitsha}} ${IMAGE}
      #     docker push ${IMAGE}
      
      #Login to Openshift using OC SA and Token of respective env. for Pod labelling - Silver
      - name: Authenticate OC Env Specific SA - Silver
        uses: redhat-actions/oc-login@v1
        env:
          OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
          OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_Env_DEPLOYER_NAME}}
        with:
          openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL_SILVER}}
          openshift_token: ${{secrets.OPENSHIFT_SA_ENV_DEPLOYER_TOKEN_SILVER}}
          namespace: ${OPENSHIFT_NAMESPACE}

      # Labels the deployment config of the application jag-ccd-1-1 with release version number to spin up the pods labelled in same version - Silver
      - name: Labelling DC of jag-ccd-1-1 to release version - Silver
        env:
          releaseVersion: ${{ env.releaseVersion }}
          appName: ${{github.event.inputs.app1}}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
        run: |
          oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'
      
       # Wait to DC rollout of jag-ccd-1-1 to get completed before proceeding next stage - Silver
      - name: Wait for DC rollout of jag-ccd-1-1 - Silver
        env:
          appName: ${{github.event.inputs.app1}}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
        run: |
          oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch

      # Labels the deployment config of the application jag-ccd-1-2 with release version number to spin up the pods labelled in same version - Silver
      - name: Labelling DC of jag-ccd-1-2 to release version - Silver
        env:
          releaseVersion: ${{ env.releaseVersion }}
          appName: ${{github.event.inputs.app2}}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
        run: |
          oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'

      # Wait to DC rollout of jag-ccd-1-2 to get completed before proceeding next stage - Silver
      - name: Wait for DC rollout of jag-ccd-1-2 - Silver
        env:
          appName: ${{github.event.inputs.app2}}
          openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE_SILVER}}-${{ github.event.inputs.env }}
        run: |
          oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch

      # #Login to Openshift using OC SA and Token of respective env. for Pod labelling - Kamloops (OC PROD)
      # - name: Authenticate OC Env Specific SA - Kamloops (OC PROD)
      #   uses: redhat-actions/oc-login@v1
      #   env:
      #     OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #     OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_Env_DEPLOYER_NAME}}
      #   with:
      #     openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL}}
      #     openshift_token: ${{secrets.OPENSHIFT_SA_ENV_DEPLOYER_TOKEN}}
      #     namespace: ${OPENSHIFT_NAMESPACE}
        
      # # Labels the deployment config of the application jag-ccd-1-1 with release version number to spin up the pods labelled in same version - Kamloops (OC PROD)
      # - name: Labelling DC of jag-ccd-1-1 to release version - Kamloops (OC PROD)
      #   env:
      #     releaseVersion: ${{ env.releaseVersion }}
      #     appName: ${{github.event.inputs.app1}}
      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #   run: |
      #     oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'
      
      # # Wait to DC rollout of jag-ccd-1-1 to get completed before proceeding next stage - Kamloops (OC PROD)
      # - name: Wait for DC rollout of jag-ccd-1-1 - Kamloops (OC PROD)
      #   env:
      #     appName: ${{github.event.inputs.app1}}
      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #   run: |
      #     oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch

      # # Labels the deployment config of the application jag-ccd-1-2 with release version number to spin up the pods labelled in same version - Kamloops (OC PROD)
      # - name: Labelling DC of jag-ccd-1-2 to release version - Kamloops (OC PROD)
      #   env:
      #     releaseVersion: ${{ env.releaseVersion }}
      #     appName: ${{github.event.inputs.app2}}
      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #   run: |
      #     oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'
      
      # # Wait to DC rollout of jag-ccd-1-2 to get completed before proceeding next stage - Kamloops (OC PROD)
      # - name: Wait for DC rollout of jag-ccd-1-2 - Kamloops (OC PROD)
      #   env:
      #     appName: ${{github.event.inputs.app2}}
      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #   run: |
      #     oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch
      
      # #Login to Openshift using OC SA and Token of respective env. for Pod labelling - Calgary (OC DR)
      # - name: Authenticate OC Env Specific SA - Calgary (OC DR)
      #   uses: redhat-actions/oc-login@v1
      #   env:
      #     OPENSHIFT_NAMESPACE: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #     OPENSHIFT_USER: ${{secrets.OPENSHIFT_SA_Env_DEPLOYER_NAME}}
      #   with:
      #     openshift_server_url: ${{secrets.OPENSHIFT_SERVER_URL_DR}}
      #     openshift_token: ${{secrets.OPENSHIFT_SA_ENV_DEPLOYER_TOKEN_DR}}
      #     namespace: ${OPENSHIFT_NAMESPACE}
        
      # # Labels the deployment config of the application jag-ccd-1-1 with release version number to spin up the pods labelled in same version - Calgary (OC DR)
      # - name: Labelling DC of jag-ccd-1-1 to release version - Calgary (OC DR)
      #   env:
      #     releaseVersion: ${{ env.releaseVersion }}
      #     appName: ${{github.event.inputs.app1}}
      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #   run: |
      #     oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'
      
      # # Wait to DC rollout of jag-ccd-1-1 to get completed before proceeding next stage - Calgary (OC DR)
      # - name: Wait for DC rollout of jag-ccd-1-1 - Calgary (OC DR)
      #   env:
      #     appName: ${{github.event.inputs.app1}}
      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #   run: |
      #     oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch

      # # Labels the deployment config of the application jag-ccd-1-2 with release version number to spin up the pods labelled in same version - Calgary (OC DR)
      # - name: Labelling DC of jag-ccd-1-2 to release version - Calgary (OC DR)
      #   env:
      #     releaseVersion: ${{ env.releaseVersion }}
      #     appName: ${{github.event.inputs.app2}}
      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #   run: |
      #     oc patch dc ${appName} -n ${openshiftEnvNamespace} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"${{ env.releaseVersion }}.${{ env.gitsha }}"}}}}}'
      
      # # Wait to DC rollout of jag-ccd-1-2 to get completed before proceeding next stage - Calgary (OC DR)
      # - name: Wait for DC rollout of jag-ccd-1-2 - Calgary (OC DR)
      #   env:
      #     appName: ${{github.event.inputs.app2}}
      #     openshiftEnvNamespace: ${{secrets.OPENSHIFT_LICENSE_PLATE}}-${{ github.event.inputs.env }}
      #   run: |
      #     oc rollout status -n ${openshiftEnvNamespace} dc/${appName} --watch

      - name: Run Integration Tests
        env:
          TEST_STARTER_URL: ${{secrets.TEST_STARTER_URL}}
          BASIC_AUTH_USER: ${{secrets.BASIC_AUTH_USER}}
          BASIC_AUTH_PASS: ${{secrets.BASIC_AUTH_PASS}}
        run: |
          RET=`curl --write-out '%{content_type}' --output TestErrors.zip --request GET --user ${BASIC_AUTH_USER}:${BASIC_AUTH_PASS} --url ${TEST_STARTER_URL}`
          if [ "$RET" = "application/zip" ]; then
          echo "Status: Failed Integration Test(s) found!"
          exit 1
          fi
          if [[ "$RET" == *"json"* ]]; then
          echo "Status: All Tests Passed"
          fi
          if [ "$RET" != "application/zip" ] && [[ "$RET" != *"json"* ]]; then
          echo "Received content_type is $RET, was expecting json or zip"
          exit 1
          fi

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3.1.1
        if: failure()
        with:
          name: integration-tests-report
          path: |
            TestErrors.zip
          retention-days: 5
